easy_admin:
    entities:
        Produit:
            class: App\Entity\Produit
            form:
                fields:
                - { property: 'description', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
            label: 'Produits'
            list:
                title: "Les plus récents de nos produits"
