easy_admin:
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"

    entities:
        Produit:
            class: App\Entity\Produit
            label: 'Produits'
            list:
                title: "Les plus récents de nos produits"
